extern const GeoLayout vcutm_area_1_geo[];
extern const GeoLayout vcutm_area_1[];
extern const Collision vcutm_area_1_collision[];
extern const MacroObject vcutm_area_1_macro_objs[];
extern u8 vcutm_dl_SUPER_MARIO_64_49A3631E_0_2_all_ci8[];
extern u8 vcutm_dl_SUPER_MARIO_64_49A3631E_0_2_all_pal_rgba16[];
extern u8 vcutm_dl_SUPER_MARIO_64_49A3631E_0_2_all_ci8_copy[];
extern u8 vcutm_dl_SUPER_MARIO_64_49A3631E_0_2_all_pal_rgba16_copy[];
extern u8 vcutm_dl_SUPER_MARIO_64_49A3631E_0_2_all_ci8_copy_copy[];
extern u8 vcutm_dl_SUPER_MARIO_64_49A3631E_0_2_all_pal_rgba16_copy_copy[];
extern u8 vcutm_dl_SUPER_MARIO_64_49A3631E_0_2_all_ci8_copy_copy_copy[];
extern u8 vcutm_dl_SUPER_MARIO_64_49A3631E_0_2_all_pal_rgba16_copy_copy_copy[];
extern u8 vcutm_dl_transparent_ia8[];
extern Vtx vcutm_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx vcutm_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx vcutm_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx vcutm_dl_Cube_001_mesh_layer_1_vtx_cull[8];
extern Vtx vcutm_dl_Cube_001_mesh_layer_1_vtx_0[24];
extern Gfx vcutm_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx vcutm_dl_Cube_002_mesh_layer_1_vtx_cull[8];
extern Vtx vcutm_dl_Cube_002_mesh_layer_1_vtx_0[24];
extern Gfx vcutm_dl_Cube_002_mesh_layer_1_tri_0[];
extern Vtx vcutm_dl_Cube_003_mesh_layer_1_vtx_cull[8];
extern Vtx vcutm_dl_Cube_003_mesh_layer_1_vtx_0[24];
extern Gfx vcutm_dl_Cube_003_mesh_layer_1_tri_0[];
extern Vtx vcutm_dl_death_plane_mesh_layer_5_vtx_cull[8];
extern Vtx vcutm_dl_death_plane_mesh_layer_5_vtx_0[4];
extern Gfx vcutm_dl_death_plane_mesh_layer_5_tri_0[];
extern Gfx mat_vcutm_dl_Fast3D_Material[];
extern Gfx mat_revert_vcutm_dl_Fast3D_Material[];
extern Gfx mat_vcutm_dl_Fast3D_Material_003[];
extern Gfx mat_revert_vcutm_dl_Fast3D_Material_003[];
extern Gfx mat_vcutm_dl_Fast3D_Material_004[];
extern Gfx mat_revert_vcutm_dl_Fast3D_Material_004[];
extern Gfx mat_vcutm_dl_Fast3D_Material_005[];
extern Gfx mat_revert_vcutm_dl_Fast3D_Material_005[];
extern Gfx mat_vcutm_dl_Fast3D_Material_001[];
extern Gfx mat_revert_vcutm_dl_Fast3D_Material_001[];
extern Gfx vcutm_dl_Cube_mesh_layer_1[];
extern Gfx vcutm_dl_Cube_001_mesh_layer_1[];
extern Gfx vcutm_dl_Cube_002_mesh_layer_1[];
extern Gfx vcutm_dl_Cube_003_mesh_layer_1[];
extern Gfx vcutm_dl_death_plane_mesh_layer_5[];
