extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern u8 ccm_dl_SUPER_MARIO_64_AEF22277_0_2_all_ci8[];
extern u8 ccm_dl_SUPER_MARIO_64_AEF22277_0_2_all_pal_rgba16[];
extern u8 ccm_dl_SUPER_MARIO_64_AEF22277_0_2_all_ci8_copy[];
extern u8 ccm_dl_SUPER_MARIO_64_AEF22277_0_2_all_pal_rgba16_copy[];
extern Vtx ccm_dl_act3parkourstar_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_act3parkourstar_mesh_layer_1_vtx_0[24];
extern Gfx ccm_dl_act3parkourstar_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_level_mesh_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_level_mesh_mesh_layer_1_vtx_0[246];
extern Gfx ccm_dl_level_mesh_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_level_mesh_mesh_layer_1_vtx_1[57];
extern Gfx ccm_dl_level_mesh_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_level_mesh_001_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_level_mesh_001_mesh_layer_1_vtx_0[813];
extern Gfx ccm_dl_level_mesh_001_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_level_mesh_001_mesh_layer_1_vtx_1[506];
extern Gfx ccm_dl_level_mesh_001_mesh_layer_1_tri_1[];
extern Gfx mat_ccm_dl_wowie[];
extern Gfx mat_revert_ccm_dl_wowie[];
extern Gfx mat_ccm_dl_walls[];
extern Gfx mat_revert_ccm_dl_walls[];
extern Gfx mat_ccm_dl_floor[];
extern Gfx mat_revert_ccm_dl_floor[];
extern Gfx mat_ccm_dl_grass[];
extern Gfx mat_revert_ccm_dl_grass[];
extern Gfx mat_ccm_dl_grass_001[];
extern Gfx mat_revert_ccm_dl_grass_001[];
extern Gfx ccm_dl_act3parkourstar_mesh_layer_1[];
extern Gfx ccm_dl_level_mesh_mesh_layer_1[];
extern Gfx ccm_dl_level_mesh_001_mesh_layer_1[];
