extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern u8 ccm_dl_SUPER_MARIO_64_27ECE31D_0_2_all_ci8[];
extern u8 ccm_dl_SUPER_MARIO_64_27ECE31D_0_2_all_pal_rgba16[];
extern Vtx ccm_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Plane_mesh_layer_1_vtx_0[1020];
extern Gfx ccm_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_ccm_dl_Fast3D_Material[];
extern Gfx mat_revert_ccm_dl_Fast3D_Material[];
extern Gfx ccm_dl_Plane_mesh_layer_1[];
