extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern u8 ccm_dl_SUPER_MARIO_64_27ECE31D_0_2_all_ci8[];
extern u8 ccm_dl_SUPER_MARIO_64_27ECE31D_0_2_all_pal_rgba16[];
extern Vtx ccm_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Plane_mesh_layer_1_vtx_0[1015];
extern Gfx ccm_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Plane_mesh_layer_1_vtx_1[96];
extern Gfx ccm_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_Plane_mesh_layer_1_vtx_2[47];
extern Gfx ccm_dl_Plane_mesh_layer_1_tri_2[];
extern Gfx mat_ccm_dl_Fast3D_Material[];
extern Gfx mat_revert_ccm_dl_Fast3D_Material[];
extern Gfx mat_ccm_dl_walls_for_the_building[];
extern Gfx mat_revert_ccm_dl_walls_for_the_building[];
extern Gfx mat_ccm_dl_ceilingandfloor_for_building[];
extern Gfx mat_revert_ccm_dl_ceilingandfloor_for_building[];
extern Gfx ccm_dl_Plane_mesh_layer_1[];
