extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern u8 castle_grounds_dl_SUPER_MARIO_64_3FF93DA3_0_2_all_i8[];
extern Vtx castle_grounds_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Cube_mesh_layer_1_vtx_0[30];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_room_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_room_mesh_layer_1_vtx_0[24];
extern Gfx castle_grounds_dl_room_mesh_layer_1_tri_0[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_002[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_002[];
extern Gfx mat_castle_grounds_dl_f3dlite_material[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material[];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1[];
extern Gfx castle_grounds_dl_room_mesh_layer_1[];
