extern const GeoLayout wmotr_area_1_geo[];
extern const GeoLayout wmotr_area_1[];
extern const Collision wmotr_area_1_collision[];
extern const MacroObject wmotr_area_1_macro_objs[];
extern u8 wmotr_dl_water_ia8[];
extern Vtx wmotr_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx wmotr_dl_Cube_mesh_layer_1_vtx_0[367];
extern Gfx wmotr_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx wmotr_dl_Plane_mesh_layer_5_vtx_cull[8];
extern Vtx wmotr_dl_Plane_mesh_layer_5_vtx_0[7];
extern Gfx wmotr_dl_Plane_mesh_layer_5_tri_0[];
extern Gfx mat_wmotr_dl_Fast3D_Material_001[];
extern Gfx mat_revert_wmotr_dl_Fast3D_Material_001[];
extern Gfx mat_wmotr_dl_Water_f3d[];
extern Gfx mat_revert_wmotr_dl_Water_f3d[];
extern Gfx wmotr_dl_Cube_mesh_layer_1[];
extern Gfx wmotr_dl_Plane_mesh_layer_5[];
