extern const GeoLayout bits_area_1_geo[];
extern const GeoLayout bits_area_1[];
extern const Collision bits_area_1_collision[];
extern const MacroObject bits_area_1_macro_objs[];
extern u8 bits_dl_SUPER_MARIO_64_4C001AD4_0_2_all_ci8[];
extern u8 bits_dl_SUPER_MARIO_64_4C001AD4_0_2_all_pal_rgba16[];
extern u8 bits_dl_SUPER_MARIO_64_10E452C9_0_2_all_i8[];
extern u8 bits_dl_SUPER_MARIO_64_1448C073_0_2_all_ci8[];
extern u8 bits_dl_SUPER_MARIO_64_1448C073_0_2_all_pal_rgba16[];
extern u8 bits_dl_SUPER_MARIO_64_3F817C21_0_2_all_ci8[];
extern u8 bits_dl_SUPER_MARIO_64_3F817C21_0_2_all_pal_rgba16[];
extern Vtx bits_dl_bowserhead_mesh_layer_1_vtx_cull[8];
extern Vtx bits_dl_bowserhead_mesh_layer_1_vtx_0[420];
extern Gfx bits_dl_bowserhead_mesh_layer_1_tri_0[];
extern Vtx bits_dl_bowserhead_mesh_layer_1_vtx_1[330];
extern Gfx bits_dl_bowserhead_mesh_layer_1_tri_1[];
extern Vtx bits_dl_bowserhead_mesh_layer_1_vtx_2[162];
extern Gfx bits_dl_bowserhead_mesh_layer_1_tri_2[];
extern Vtx bits_dl_bowserhead_mesh_layer_1_vtx_3[231];
extern Gfx bits_dl_bowserhead_mesh_layer_1_tri_3[];
extern Vtx bits_dl_lava_mesh_layer_1_vtx_cull[8];
extern Vtx bits_dl_lava_mesh_layer_1_vtx_0[4];
extern Gfx bits_dl_lava_mesh_layer_1_tri_0[];
extern Gfx mat_bits_dl_f3dlite_material_002[];
extern Gfx mat_revert_bits_dl_f3dlite_material_002[];
extern Gfx mat_bits_dl_dark_bricks[];
extern Gfx mat_revert_bits_dl_dark_bricks[];
extern Gfx mat_bits_dl_tiled_floor[];
extern Gfx mat_revert_bits_dl_tiled_floor[];
extern Gfx mat_bits_dl_f3dlite_material_001[];
extern Gfx mat_revert_bits_dl_f3dlite_material_001[];
extern Gfx mat_bits_dl_f3dlite_material[];
extern Gfx mat_revert_bits_dl_f3dlite_material[];
extern Gfx bits_dl_bowserhead_mesh_layer_1[];
extern Gfx bits_dl_lava_mesh_layer_1[];
