extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern u8 wf_dl_SUPER_MARIO_64_3C99819F_0_2_all_ci8[];
extern u8 wf_dl_SUPER_MARIO_64_3C99819F_0_2_all_pal_rgba16[];
extern Vtx wf_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_Plane_mesh_layer_1_vtx_0[64];
extern Gfx wf_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_wf_dl_f3dlite_material[];
extern Gfx mat_revert_wf_dl_f3dlite_material[];
extern Gfx wf_dl_Plane_mesh_layer_1[];
