extern const GeoLayout jrb_area_1_geo[];
extern const GeoLayout jrb_area_1[];
extern const Collision jrb_area_1_collision[];
extern const MacroObject jrb_area_1_macro_objs[];
extern u8 jrb_dl_SUPER_MARIO_64_7A1B62B1_0_2_all_ci8[];
extern u8 jrb_dl_SUPER_MARIO_64_7A1B62B1_0_2_all_pal_rgba16[];
extern u8 jrb_dl_SUPER_MARIO_64_130CA9A8_0_2_all_ci8[];
extern u8 jrb_dl_SUPER_MARIO_64_130CA9A8_0_2_all_pal_rgba16[];
extern u8 jrb_dl_SUPER_MARIO_64_144C8CF3_0_2_all_ci8[];
extern u8 jrb_dl_SUPER_MARIO_64_144C8CF3_0_2_all_pal_rgba16[];
extern Vtx jrb_dl_Level_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Level_Mesh_mesh_layer_1_vtx_0[16];
extern Gfx jrb_dl_Level_Mesh_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Level_Mesh_mesh_layer_1_vtx_1[4];
extern Gfx jrb_dl_Level_Mesh_mesh_layer_1_tri_1[];
extern Vtx jrb_dl_Level_Mesh_mesh_layer_1_vtx_2[4];
extern Gfx jrb_dl_Level_Mesh_mesh_layer_1_tri_2[];
extern Vtx jrb_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Plane_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Plane_001_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Plane_001_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Plane_002_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Plane_002_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Plane_002_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_table_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_table_mesh_layer_1_vtx_0[234];
extern Gfx jrb_dl_table_mesh_layer_1_tri_0[];
extern Gfx mat_jrb_dl_walls[];
extern Gfx mat_revert_jrb_dl_walls[];
extern Gfx mat_jrb_dl_floor[];
extern Gfx mat_revert_jrb_dl_floor[];
extern Gfx mat_jrb_dl_ceiling[];
extern Gfx mat_revert_jrb_dl_ceiling[];
extern Gfx mat_jrb_dl_f3dlite_material_001[];
extern Gfx mat_revert_jrb_dl_f3dlite_material_001[];
extern Gfx mat_jrb_dl_f3dlite_material_002[];
extern Gfx mat_revert_jrb_dl_f3dlite_material_002[];
extern Gfx mat_jrb_dl_f3dlite_material_003[];
extern Gfx mat_revert_jrb_dl_f3dlite_material_003[];
extern Gfx mat_jrb_dl_f3dlite_material[];
extern Gfx mat_revert_jrb_dl_f3dlite_material[];
extern Gfx jrb_dl_Level_Mesh_mesh_layer_1[];
extern Gfx jrb_dl_Plane_mesh_layer_1[];
extern Gfx jrb_dl_Plane_001_mesh_layer_1[];
extern Gfx jrb_dl_Plane_002_mesh_layer_1[];
extern Gfx jrb_dl_table_mesh_layer_1[];
