extern const GeoLayout bowser_3_area_1_geo[];
extern const GeoLayout bowser_3_area_1[];
extern const Collision bowser_3_area_1_collision[];
extern const MacroObject bowser_3_area_1_macro_objs[];
extern u8 bowser_3_dl_SUPER_MARIO_64_1C62CC15_0_2_all_ci8[];
extern u8 bowser_3_dl_SUPER_MARIO_64_1C62CC15_0_2_all_pal_rgba16[];
extern u8 bowser_3_dl_chain_ci8[];
extern u8 bowser_3_dl_chain_pal_rgba16[];
extern u8 bowser_3_dl_SUPER_MARIO_64_52BC0E5E_0_2_all_ci8[];
extern u8 bowser_3_dl_SUPER_MARIO_64_52BC0E5E_0_2_all_pal_rgba16[];
extern u8 bowser_3_dl_windtexture_i8[];
extern Vtx bowser_3_dl_cage_mesh_layer_4_vtx_cull[8];
extern Vtx bowser_3_dl_cage_mesh_layer_4_vtx_0[30];
extern Gfx bowser_3_dl_cage_mesh_layer_4_tri_0[];
extern Vtx bowser_3_dl_chains_mesh_layer_4_vtx_cull[8];
extern Vtx bowser_3_dl_chains_mesh_layer_4_vtx_0[4];
extern Gfx bowser_3_dl_chains_mesh_layer_4_tri_0[];
extern Vtx bowser_3_dl_death_plane_mesh_layer_5_vtx_cull[8];
extern Vtx bowser_3_dl_death_plane_mesh_layer_5_vtx_0[4];
extern Gfx bowser_3_dl_death_plane_mesh_layer_5_tri_0[];
extern Vtx bowser_3_dl_level_mesh_mesh_layer_1_vtx_cull[8];
extern Vtx bowser_3_dl_level_mesh_mesh_layer_1_vtx_0[536];
extern Gfx bowser_3_dl_level_mesh_mesh_layer_1_tri_0[];
extern Vtx bowser_3_dl_Sphere_mesh_layer_5_vtx_cull[8];
extern Vtx bowser_3_dl_Sphere_mesh_layer_5_vtx_0[239];
extern Gfx bowser_3_dl_Sphere_mesh_layer_5_tri_0[];
extern Gfx mat_bowser_3_dl_f3dlite_material_003[];
extern Gfx mat_revert_bowser_3_dl_f3dlite_material_003[];
extern Gfx mat_bowser_3_dl_chain[];
extern Gfx mat_revert_bowser_3_dl_chain[];
extern Gfx mat_bowser_3_dl_f3dlite_material_004[];
extern Gfx mat_revert_bowser_3_dl_f3dlite_material_004[];
extern Gfx mat_bowser_3_dl_f3dlite_material[];
extern Gfx mat_revert_bowser_3_dl_f3dlite_material[];
extern Gfx mat_bowser_3_dl_f3dlite_material_002[];
extern Gfx mat_revert_bowser_3_dl_f3dlite_material_002[];
extern Gfx bowser_3_dl_cage_mesh_layer_4[];
extern Gfx bowser_3_dl_chains_mesh_layer_4[];
extern Gfx bowser_3_dl_death_plane_mesh_layer_5[];
extern Gfx bowser_3_dl_level_mesh_mesh_layer_1[];
extern Gfx bowser_3_dl_Sphere_mesh_layer_5[];
