extern const GeoLayout pss_area_1_geo[];
extern const GeoLayout pss_area_1[];
extern const Collision pss_area_1_collision[];
extern const MacroObject pss_area_1_macro_objs[];
extern u8 pss_dl_SUPER_MARIO_64_2B08F032_0_2_all_i8[];
extern u8 pss_dl_earth_rgba16[];
extern Vtx pss_dl_deathplane_mesh_layer_5_vtx_cull[8];
extern Vtx pss_dl_deathplane_mesh_layer_5_vtx_0[4];
extern Gfx pss_dl_deathplane_mesh_layer_5_tri_0[];
extern Vtx pss_dl_level_mesh_mesh_layer_1_vtx_cull[8];
extern Vtx pss_dl_level_mesh_mesh_layer_1_vtx_0[284];
extern Gfx pss_dl_level_mesh_mesh_layer_1_tri_0[];
extern Vtx pss_dl_Plane_mesh_layer_5_vtx_cull[8];
extern Vtx pss_dl_Plane_mesh_layer_5_vtx_0[9];
extern Gfx pss_dl_Plane_mesh_layer_5_tri_0[];
extern Gfx mat_pss_dl_f3dlite_material_002[];
extern Gfx mat_revert_pss_dl_f3dlite_material_002[];
extern Gfx mat_pss_dl_f3dlite_material[];
extern Gfx mat_revert_pss_dl_f3dlite_material[];
extern Gfx mat_pss_dl_f3dlite_material_001[];
extern Gfx mat_revert_pss_dl_f3dlite_material_001[];
extern Gfx pss_dl_deathplane_mesh_layer_5[];
extern Gfx pss_dl_level_mesh_mesh_layer_1[];
extern Gfx pss_dl_Plane_mesh_layer_5[];
