extern const GeoLayout bbh_area_1_geo[];
extern const GeoLayout bbh_area_1[];
extern const Collision bbh_area_1_collision[];
extern const MacroObject bbh_area_1_macro_objs[];
extern u8 bbh_dl_SUPER_MARIO_64_1C62CC15_0_2_all_ci8[];
extern u8 bbh_dl_SUPER_MARIO_64_1C62CC15_0_2_all_pal_rgba16[];
extern u8 bbh_dl_SUPER_MARIO_64_7E5C24F7_0_2_all_i8[];
extern u8 bbh_dl_SUPER_MARIO_64_3C99819F_0_2_all_ci8[];
extern u8 bbh_dl_SUPER_MARIO_64_3C99819F_0_2_all_pal_rgba16[];
extern Vtx bbh_dl_Level_Mesh_mesh_layer_5_vtx_cull[8];
extern Vtx bbh_dl_Level_Mesh_mesh_layer_5_vtx_0[20];
extern Gfx bbh_dl_Level_Mesh_mesh_layer_5_tri_0[];
extern Vtx bbh_dl_Level_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx bbh_dl_Level_Mesh_mesh_layer_1_vtx_0[41];
extern Gfx bbh_dl_Level_Mesh_mesh_layer_1_tri_0[];
extern Vtx bbh_dl_Level_Mesh_mesh_layer_1_vtx_1[1358];
extern Gfx bbh_dl_Level_Mesh_mesh_layer_1_tri_1[];
extern Gfx mat_bbh_dl_bars[];
extern Gfx mat_revert_bbh_dl_bars[];
extern Gfx mat_bbh_dl_bed[];
extern Gfx mat_revert_bbh_dl_bed[];
extern Gfx mat_bbh_dl_walls[];
extern Gfx mat_revert_bbh_dl_walls[];
extern Gfx bbh_dl_Level_Mesh_mesh_layer_5[];
extern Gfx bbh_dl_Level_Mesh_mesh_layer_1[];
